name: pickle_parser
description: A Flutter package for parsing pickle files and executing Cucumber steps in widget tests.
version: 1.1.0
repository: https://github.com/robrob-creator/pickle_parser.git

environment:
  sdk: ">=2.19.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  args: ^2.4.2
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
