name: pickle_parser_cli
description: Command line tools for the pickle_parser package
version: 1.0.0

environment:
  sdk: ">=2.19.5 <4.0.0"

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  io: ^1.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  pickle_parser: pickle_parser_cli
